2023-03-05 21:38:00,266 INFO    MainThread:27397 [wandb_setup.py:_flush():68] Configure stats pid to 27397
2023-03-05 21:38:00,267 INFO    MainThread:27397 [wandb_setup.py:_flush():68] Loading settings from /home2/sisodiya.bhoomendra/.config/wandb/settings
2023-03-05 21:38:00,267 INFO    MainThread:27397 [wandb_setup.py:_flush():68] Loading settings from /home2/sisodiya.bhoomendra/github/contrastive_learning/src/wandb/settings
2023-03-05 21:38:00,267 INFO    MainThread:27397 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-03-05 21:38:00,267 INFO    MainThread:27397 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'src/train/trainer.py', 'program': '/home2/sisodiya.bhoomendra/github/contrastive_learning/src/train/trainer.py'}
2023-03-05 21:38:00,267 INFO    MainThread:27397 [wandb_init.py:_log_setup():492] Logging user logs to /home2/sisodiya.bhoomendra/github/contrastive_learning/src/wandb/run-20230305_213800-gvc2d1l9/logs/debug.log
2023-03-05 21:38:00,267 INFO    MainThread:27397 [wandb_init.py:_log_setup():493] Logging internal logs to /home2/sisodiya.bhoomendra/github/contrastive_learning/src/wandb/run-20230305_213800-gvc2d1l9/logs/debug-internal.log
2023-03-05 21:38:00,268 INFO    MainThread:27397 [wandb_init.py:init():532] calling init triggers
2023-03-05 21:38:00,268 INFO    MainThread:27397 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {'dataset': {'embedding': 'InLegalBERT_emb_new.pkl', 'limit': 80, 'train_split': 0.7, 'val_split': 0.1}, 'model': {'nhead': 3, 'in_features': 768, 'out_features': 768, 'activation': 'selu', 'num_encoder_layers': 4, 'batch_size': 128}, 'train': {'lr': 5e-06, 'epochs': 15}}
2023-03-05 21:38:00,268 INFO    MainThread:27397 [wandb_init.py:init():588] starting backend
2023-03-05 21:38:00,268 INFO    MainThread:27397 [wandb_init.py:init():592] setting up manager
2023-03-05 21:38:00,271 INFO    MainThread:27397 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-05 21:38:00,276 INFO    MainThread:27397 [wandb_init.py:init():599] backend started and connected
2023-03-05 21:38:00,279 INFO    MainThread:27397 [wandb_init.py:init():687] updated telemetry
2023-03-05 21:38:00,319 INFO    MainThread:27397 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
2023-03-05 21:38:01,052 INFO    MainThread:27397 [wandb_run.py:_on_init():2134] communicating current version
2023-03-05 21:38:01,155 INFO    MainThread:27397 [wandb_run.py:_on_init():2143] got version response 
2023-03-05 21:38:01,155 INFO    MainThread:27397 [wandb_init.py:init():775] starting run threads in backend
2023-03-05 21:38:01,714 WARNING MainThread:27397 [wandb_init.py:init():1154] interrupted
Traceback (most recent call last):
  File "/home2/sisodiya.bhoomendra/venvs/python3.9_global/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1133, in init
    run = wi.init()
  File "/home2/sisodiya.bhoomendra/venvs/python3.9_global/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 787, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home2/sisodiya.bhoomendra/venvs/python3.9_global/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 273, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home2/sisodiya.bhoomendra/venvs/python3.9_global/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 120, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home2/sisodiya.bhoomendra/venvs/python3.9_global/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 116, in _wait
    return self._event.wait(timeout=timeout)
  File "/home2/sisodiya.bhoomendra/localpython/python3.9.16/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/home2/sisodiya.bhoomendra/localpython/python3.9.16/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-03-05 21:38:08,297 WARNING MsgRouterThr:27397 [router.py:message_loop():77] message_loop has been closed
